### ISSUE TITLE
Is 3.0.10+quic ready?

### ISSUE THREAD

**Issue by RafaelGSS** [quictls/openssl#136]
Hi!

At Node.js we monitor the GitHub release tags and https://github.com/quictls/openssl/releases/tag/openssl-3.0.10-quic1 is showing `OpenSSL 3.1.2 quic Release 1`. Is it just a mistype when tagging the release on GitHub or 3.0.10+quic wasn't released at all?

**Comment by tmshort** [comment]
That was a copy/paste error of the name/description when creating the 3.0.10 tag. I've since fixed it. The tag itself is correct.
The `openssl-3.0.10-quic1` tag is on the `openssl-3.0.10+quic` branch at commit c960369e66
The `openssl-3.1.2-quic1` tag is on the `openssl-3.1.2+quic` branch at commit ee904e9093
