### ISSUE TITLE
Not compiling for Windows x64

### ISSUE THREAD

**Issue by JorgeCarousel** [quictls/openssl#93]
Hello,

I'm trying to compile Openssl-3.0.5+Quic for Windows x64 using the instructions in NOTES-WINDOWS.md and when I run nmake I get this:

crypto\aes\libcrypto-shlib-aes_cfb.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
Could Not Find D:\Temp\openssl-openssl-3.0.5-quic\libcrypto-81_3-x64.*

Any idea what's going on?

Thank you.

**Comment by tmshort** [comment]
Please try using upstream openssl 3.0.5 to see if you get a similar/identical error.
AFAICT, it may be due to a dirty workspace? Possibly do a clean build. The QUIC changes don't touch any processor-specific code. It seems that you have a 32-bit object module trying to be pulled into a 64-bit library.

A Google search gives:
https://stackoverflow.com/questions/3563756/fatal-error-lnk1112-module-machine-type-x64-conflicts-with-target-machine-typ

You may need to install additional components.

**Comment by JorgeCarousel** [comment]
I believe the problem was that I used:

perl Configure

Instead of:

perl Configure VC-WIN64A

Because I just tried using the second one and it did compile.

I hope Apache adopts this so it's easier for them to build a http3 module for httpd.

Thanks.

**Comment by tmshort** [comment]
Ok, closing this out.
